In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [2]:
dataset_path = "./rockpaperscissors"
train_datagen = ImageDataGenerator(
rescale=1./255,
validation_split=0.2
)
train_generator = train_datagen.flow_from_directory(
dataset_path,
target_size=(150, 150),
batch_size=32,
class_mode='categorical',
subset='training',
)
validation_generator = train_datagen.flow_from_directory(
dataset_path,
target_size=(150, 150),
batch_size=32,
class_mode='categorical',
subset='validation',
)

Found 1751 images belonging to 3 classes.
Found 437 images belonging to 3 classes.


In [3]:
model = Sequential([
Conv2D(32, (3,3), activation= 'relu', input_shape = (150,150,3)),
MaxPooling2D(2,2),
Conv2D(64, (3,3), activation= 'relu'),
MaxPooling2D(2,2),
Conv2D(128, (3,3), activation= 'relu'),
MaxPooling2D(2,2),
Flatten(),
Dense(512,activation= 'relu'),
Dense(3, activation= 'softmax')
])

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [4]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 148, 148, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 74, 74, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 72, 72, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 36, 36, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 34, 34, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 17, 17, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 36992)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 512)            │    18,940,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │         1,539 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 19,035,203 (72.61 MB)

 Trainable params: 19,035,203 (72.61 MB)

 Non-trainable params: 0 (0.00 B)

In [5]:
model.compile(
loss='categorical_crossentropy',
optimizer='adam',
metrics=['accuracy'])

In [6]:
history = model.fit(
train_generator,
validation_data=validation_generator,
epochs=10
)

Epoch 1/10
55/55 ━━━━━━━━━━━━━━━━━━━━ 24s 400ms/step - accuracy: 0.6334 - loss: 0.8605 - val_accuracy: 0.8902 - val_loss: 0.3575
Epoch 2/10
55/55 ━━━━━━━━━━━━━━━━━━━━ 28s 517ms/step - accuracy: 0.9103 - loss: 0.2498 - val_accuracy: 0.9314 - val_loss: 0.1696
Epoch 3/10
55/55 ━━━━━━━━━━━━━━━━━━━━ 29s 525ms/step - accuracy: 0.9617 - loss: 0.1124 - val_accuracy: 0.9611 - val_loss: 0.1171
Epoch 4/10
55/55 ━━━━━━━━━━━━━━━━━━━━ 27s 487ms/step - accuracy: 0.9794 - loss: 0.0653 - val_accuracy: 0.9474 - val_loss: 0.1756
Epoch 5/10
55/55 ━━━━━━━━━━━━━━━━━━━━ 27s 494ms/step - accuracy: 0.9737 - loss: 0.0758 - val_accuracy: 0.9703 - val_loss: 0.0955
Epoch 6/10
55/55 ━━━━━━━━━━━━━━━━━━━━ 27s 498ms/step - accuracy: 0.9920 - loss: 0.0242 - val_accuracy: 0.9725 - val_loss: 0.1095
Epoch 7/10
55/55 ━━━━━━━━━━━━━━━━━━━━ 27s 484ms/step - accuracy: 0.9971 - loss: 0.0090 - val_accuracy: 0.9771 - val_loss: 0.0900
Epoch 8/10
55/55 ━━━━━━━━━━━━━━━━━━━━ 28s 502ms/step - accuracy: 0.9971 - loss: 0.0081 - val_accu

In [7]:
val_loss, val_acc = model.evaluate(validation_generator)
print(f'Validation loss: {val_loss}, Validation accuracy: {val_acc}')

14/14 ━━━━━━━━━━━━━━━━━━━━ 2s 170ms/step - accuracy: 0.9771 - loss: 0.1130
Validation loss: 0.11303132027387619, Validation accuracy: 0.9771167039871216


In [8]:
predictions = model.predict(validation_generator)
print(predictions) # Output berupa probabilitas prediksi tiap kelas

14/14 ━━━━━━━━━━━━━━━━━━━━ 3s 172ms/step
[[9.9999964e-01 6.1714765e-08 2.4188867e-07]
 [8.9765354e-16 1.4800511e-26 1.0000000e+00]
 [5.4663747e-07 6.2089723e-16 9.9999940e-01]
 ...
 [3.9686178e-08 1.0000000e+00 1.1582062e-17]
 [1.8696813e-09 1.0320839e-19 1.0000000e+00]
 [1.7735756e-16 1.1115515e-19 1.0000000e+00]]
